11 carousel
hlxsites/vg-macktrucks-com pull request #112
Opened 2023-05-24 07:15 UTC by TomaszDziezykNetcentric

Fix #11

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/tdziezyk/carousel
- After: https://11-carousel--vg-macktrucks-com--hlxsites.hlx.page/drafts/tdziezyk/carousel

2023-05-24 08:31 UTC, SantiagoHomps-NC approved these changes

2023-05-24 13:53 UTC, jonatan-lledo-netcentric approved these changes

2023-05-24 13:54 UTC, Lakshmishri requested changes
Let me know if u disagree

2023-05-24 13:54 UTC, Lakshmishri commented on blocks/carousel/carousel.js
> +  desktopControls.innerHTML = '<li><button type="button">Left</button></li><li><button type="button">Right</button></li>';
can this be changed to `createElement `and append as child ?

2023-05-24 13:54 UTC, Lakshmishri commented on blocks/carousel/carousel.js
> +    control.innerHTML = `<button type="button">${j + 1}</button>`;
same as above

2023-05-25 10:50 UTC, TomaszDziezykNetcentric commented on blocks/carousel/carousel.js
> +    control.innerHTML = `<button type="button">${j + 1}</button>`;
Done

2023-05-25 10:51 UTC, TomaszDziezykNetcentric commented on blocks/carousel/carousel.js
> +  desktopControls.innerHTML = '<li><button type="button">Left</button></li><li><button type="button">Right</button></li>';
done

2023-05-25 13:47 UTC, Lakshmishri approved these changes

2023-05-25 13:47 UTC, Lakshmishri approved these changes

2023-05-25 13:47 UTC, merged