89 feat columns
hlxsites/vg-macktrucks-com pull request #156
Opened 2023-05-30 14:11 UTC by jonatan-lledo-netcentric

Fix #89 

also trucks/
and trucks/anthem/

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/
- After: https://89-feat-columns--vg-macktrucks-com--hlxsites.hlx.page/

2023-05-30 15:39 UTC, manuel-vara approved these changes

2023-05-30 16:15 UTC, SantiagoHomps-NC commented
Some things I noticed:
-Each column in desktop view should have a `padding-right: 10%`
-The font size is a little bit bigger than it should
-When shrinking the screen there is a `padding: 0 32px;` missing

2023-05-31 08:35 UTC, TomaszDziezykNetcentric requested changes

2023-05-31 08:35 UTC, TomaszDziezykNetcentric commented on scripts/lib-franklin.js
> +function addBackgroundImage(section, picture) {
Is it a new version of Franklin lib? 
I'm asking because we shouldn't modify the lib ourselves. It could be replaced with the new Franklin version in the future which will not contains those changes.

2023-05-31 08:40 UTC, jonatan-lledo-netcentric commented on blocks/carousel/carousel.js
> +        if (selectedVideoLink) {
during my tests updating trucks pages If there's only the youtube video (that supposedly has to have both versions)
it stops the script and the carousel doesn't load completely. so I prefer to add a condition to check if this is the case or not, just to be sure the script doesn't stop

2023-05-31 08:48 UTC, jonatan-lledo-netcentric commented on scripts/lib-franklin.js
> +function addBackgroundImage(section, picture) {
maybe this has to be in scripts.js instead

2023-05-31 08:51 UTC, jonatan-lledo-netcentric commented on blocks/columns/columns.css
> +  }
what do you mean? any suggestion?

2023-05-31 09:30 UTC, TomaszDziezykNetcentric commented on blocks/columns/columns.css
> +  }
There is too many spaces before the `}`

2023-05-31 09:31 UTC, TomaszDziezykNetcentric commented on scripts/lib-franklin.js
> +function addBackgroundImage(section, picture) {
Yup, we should move it to the `scripts.js`

2023-05-31 10:02 UTC, jonatan-lledo-netcentric commented on blocks/columns/columns.css
> +  }
fixed

2023-05-31 10:04 UTC, TomaszDziezykNetcentric approved these changes

2023-05-31 10:05 UTC, merged