#152 Fix specyfication text spaces
hlxsites/vg-macktrucks-com pull request #214
Opened 2023-06-13 08:50 UTC by TomaszDziezykNetcentric

Fix #152

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/andrei.balanescu/Trucks/Anthem/Specs/
- After: https://152-spec-block-text--vg-macktrucks-com--hlxsites.hlx.page/drafts/andrei.balanescu/Trucks/Anthem/Specs/

2023-06-14 06:34 UTC, jonatan-lledo-netcentric requested changes

2023-06-14 06:34 UTC, jonatan-lledo-netcentric commented on blocks/specifications/specifications.css
> +  min-height: 65px;
your solution is good, but adding the following is better:
```flex: 1 1 auto;```

2023-06-14 07:56 UTC, TomaszDziezykNetcentric commented on blocks/specifications/specifications.css
> +  min-height: 65px;
I think that the `flex: 1 1 auto` is not what was expected.
The prod: 
<img width="1178" alt="obraz" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125962117/d451f04d-0652-41ca-8cbd-59803f526586">
And the flex version:
<img width="1200" alt="obraz" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125962117/188847bc-26c6-49b0-bd3f-8d6bd45f41ad">
The current fix
<img width="1216" alt="obraz" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125962117/662c81c9-766a-4f87-9e0a-34d1ce555b94">

2023-06-14 08:01 UTC, TomaszDziezykNetcentric commented on blocks/specifications/specifications.css
> +  min-height: 65px;
@SantiagoHomps-NC maybe you can tell us if it was intentional :)?

2023-06-14 15:26 UTC, jonatan-lledo-netcentric approved these changes

2023-06-15 09:37 UTC, SantiagoHomps-NC approved these changes

2023-06-15 09:37 UTC, SantiagoHomps-NC commented on blocks/specifications/specifications.css
> +  min-height: 65px;
I think this works fine, and its solves the mobile view issue.

2023-06-15 09:41 UTC, merged