16 sidebar related news
hlxsites/vg-macktrucks-com pull request #27
Opened 2023-03-20 09:51 UTC by TomaszDziezykNetcentric

Fix #16 

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/manuel.vara/mack-news/2021/mack-displays-breadth-of-mack-granite-model-lineup-with-augmented-reality
- After: https://16-sidebar-related-news--vg-macktrucks-com--hlxsites.hlx.page/drafts/manuel.vara/mack-news/2021/mack-displays-breadth-of-mack-granite-model-lineup-with-augmented-reality

2023-03-20 11:11 UTC, jonatan-lledo-netcentric requested changes

2023-03-21 09:45 UTC, TomaszDziezykNetcentric commented on scripts/scripts.js
> +    /*
Commented code removed

2023-03-22 07:45 UTC, manuel-vara commented on blocks/fragment/fragment.js
> +    const hr = document.createElement('hr');
Are we sure we absolutely need this one? Please be aware this block can be reused on every content page, so it should remain as generic as possible.

2023-03-28 09:08 UTC, TomaszDziezykNetcentric commented on blocks/fragment/fragment.js
> +    const hr = document.createElement('hr');
I removed the `hr` element from `fragment.js`.
I added some CSS for the fragment when it is on the mack news page only.

BTW I change the 
```
block.closest('.section').classList.add(...fragmentSection.classList);
block.closest('.fragment-wrapper').replaceWith(...fragmentSection.childNodes);
```
with
```
block.classList.add(...fragmentSection.classList, 'fragment');
block.replaceChildren(...fragmentSection.childNodes);
```
before the classes were added to the news section but it should be added to the fragment block
From the user perspective it looks the same.

2023-03-29 07:03 UTC, manuel-vara commented on blocks/fragment/fragment.js
> +    const hr = document.createElement('hr');
Thanks

2023-03-29 07:06 UTC, manuel-vara commented
Can you have a look to pagespeed insights report and try to implement some of the opportunities for improvement of the speed index, please?

2023-03-31 11:52 UTC, TomaszDziezykNetcentric commented
> Can you have a look to pagespeed insights report and try to implement some of the opportunities for improvement of the speed index, please?

Now it should be fine

2023-03-31 11:55 UTC, manuel-vara approved these changes

2023-04-07 09:44 UTC, merged