fix arrow key navigation
hlxsites/vg-macktrucks-com pull request #341
Opened 2023-06-30 07:59 UTC by Lakshmishri

Fix #<330>

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/
- After: https://autosuggest-arrow-navigation--vg-macktrucks-com--hlxsites.hlx.page/

2023-06-30 09:43 UTC, TomaszDziezykNetcentric requested changes

2023-06-30 09:43 UTC, TomaszDziezykNetcentric commented on blocks/search/search.js
> +        removeClass(liSelected, 'autosuggest__results-item--highlighted');
The class `autosuggest__results-item--highlighted` is used multiple times, could we move it to the variable? It is easy to make typo and break it.

2023-06-30 10:01 UTC, jonatan-lledo-netcentric commented on blocks/search/search.js
> +  function removeClass(el, className) {
also, another way is use toggle() function with a 2nd boolean parameter to add or remove it conditionally

2023-06-30 11:06 UTC, Lakshmishri commented on blocks/header/header.js
> +    document.body.addEventListener('click', (event) => {
This is updated

2023-06-30 12:05 UTC, jonatan-lledo-netcentric approved these changes

2023-07-03 14:42 UTC, TomaszDziezykNetcentric approved these changes

2023-07-04 07:22 UTC, merged