Added class checker for new tab
hlxsites/vg-macktrucks-com pull request #371
Opened 2023-07-04 10:09 UTC by SantiagoHomps-NC

Fix #369
Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/parts-and-services/parts/partsasist/
- After: https://369-partsasist-tab--vg-macktrucks-com--hlxsites.hlx.page/parts-and-services/parts/partsasist/

2023-07-04 10:53 UTC, jonatan-lledo-netcentric approved these changes

2023-07-04 10:53 UTC, jonatan-lledo-netcentric commented on blocks/hero/hero.js
> +  const link = contentWrapper.querySelector('a');
what if the Hero has multiple CTAs?

2023-07-05 07:56 UTC, TomaszDziezykNetcentric approved these changes

2023-07-05 11:58 UTC, TomaszDziezykNetcentric requested changes

2023-07-05 11:58 UTC, TomaszDziezykNetcentric commented on scripts/scripts.js
> +  if (newTab === 'new tab') {
I was waiting till we reach the case where the text content makes a difference :)
I'm skeptical about this change, but I don't know how to achieve it in another way :(
What if the content editor would like to add a link whose content starts with `new tab-`? I know that the probability of this happening is not high, but life is brutal :)
The syntax with `-` doesn't attract attention. I would suggest something less common in the text like square brackets: `[new tab]Click me!`. It will be harder to develop, but the syntax get the editor's attention.
I wonder if in the future we will want to support more than just a new tab.
 If so, we could add syntax that would support multiple variants, but probably no need for now.
 What do you think about syntax:
 `[new tab, some other type]Click me!`?

2023-07-05 12:23 UTC, jonatan-lledo-netcentric commented on scripts/scripts.js
> +  if (newTab === 'new tab') {
agree, we have to cover the majority of the cases possible

2023-07-05 13:42 UTC, jonatan-lledo-netcentric approved these changes

2023-07-05 13:42 UTC, TomaszDziezykNetcentric requested changes

2023-07-05 14:17 UTC, TomaszDziezykNetcentric approved these changes

2023-07-05 14:29 UTC, merged