35 search
hlxsites/vg-macktrucks-com pull request #65
Opened 2023-05-05 08:15 UTC by Lakshmishri

Fix #<35>

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/search
- After: https://35search--vg-macktrucks-com--hlxsites.hlx.page/

2023-05-10 11:15 UTC, jonatan-lledo-netcentric commented on blocks/search/search.js
> +      apikey: 'zfGguNvhbqnDbWGO3UAnZuYTfx5EzYjYy5hTqS2apeg',
It has to be here the API key?

2023-05-11 11:35 UTC, TomaszDziezykNetcentric requested changes

2023-05-11 11:35 UTC, TomaszDziezykNetcentric commented on blocks/header/header.css
> +/* serach studo css */
Typo

2023-05-11 11:35 UTC, TomaszDziezykNetcentric commented on scripts/lib-franklin.js
> +export async function loadScript(url, attrs) {
Are you updating the Franklin lib version to the newer, or did you edit this file yourself? We shouldn't add a new function to this file because it is an external dependency.

2023-05-11 11:35 UTC, TomaszDziezykNetcentric commented on scripts/lib-franklin.js
> +export async function loadScript(url, attrs) {
BTW it looks like this function is already in the franklin-lib
<img width="1464" alt="obraz" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125962117/1da910b5-2ee8-4ab3-b1e5-bb9ede3285d0">

2023-05-11 12:48 UTC, Lakshmishri commented on scripts/lib-franklin.js
> +export async function loadScript(url, attrs) {
this is result auto merge in git from main. resolved it manually and pushed.

2023-05-12 06:56 UTC, jonatan-lledo-netcentric approved these changes

2023-05-15 06:54 UTC, TomaszDziezykNetcentric commented on blocks/header/header.css
> +/* serach studio css */
typo
should be `search` ;)

2023-05-15 06:58 UTC, TomaszDziezykNetcentric approved these changes

2023-05-17 08:53 UTC, merged