Magazine date format #431
hlxsites/vg-macktrucks-com pull request #726
Opened 2024-05-28 18:06 UTC by santi-homps

Fix #431

Made avaliable for the future magazine template work the date format in the selected language and options by setting them in the constants files.

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/
- After: https://magazine-date-format--vg-macktrucks-com--hlxsites.hlx.page/

2024-05-29 09:48 UTC, jonatan-lledo-netcentric requested changes

2024-05-29 09:48 UTC, jonatan-lledo-netcentric commented on templates/magazine/magazine.js
> +  const localeDate = date.toLocaleDateString(DATE_LANGUAGE, extractedOptions);
there is a better and more modern way to format dates `Intl.DateTimeFormat`. see more in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat). try this instead.

2024-05-29 14:01 UTC, jonatan-lledo-netcentric approved these changes

2024-05-30 06:40 UTC, amglebihan approved these changes

2024-05-30 12:52 UTC, merged