FR: video in hero #589
hlxsites/vg-macktrucks-com pull request #737
Opened 2024-06-05 12:09 UTC by amglebihan

Fix #589

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/alan/v2-hero
- After: https://589-fr-video-in-hero--vg-macktrucks-com--hlxsites.hlx.page/drafts/alan/v2-hero

2024-06-05 13:32 UTC, amglebihan commented on styles/styles.css
> +  fill: var(--button-secondary-gold-hover);
Done.

2024-06-05 13:51 UTC, amglebihan commented on styles/styles.css
> +}
Done, although the outline appears to be cut off due to the position of the button.

<img width="82" alt="button-outline" src="https://github.com/hlxsites/vg-macktrucks-com/assets/166131459/b77f8b8e-9f57-44b9-baee-fbf6c2841f25">

2024-06-05 14:02 UTC, jonatan-lledo-netcentric approved these changes

2024-06-05 14:27 UTC, amglebihan commented on styles/styles.css
> +  height: 48px;
Done.

2024-06-06 06:46 UTC, alexiscoelho requested changes

2024-06-06 07:03 UTC, amglebihan commented on scripts/video-helper.js
> +  applyAttributes(video, props);
Indeed, I overlooked that. Changed.

2024-06-06 07:07 UTC, alexiscoelho approved these changes

2024-06-06 07:21 UTC, amglebihan commented on scripts/video-helper.js
> +  applyAttributes(video, props);
I had to revert some code because passing props to createElement wasn't setting the attributes' values correctly. Specifically, instead of getting `autoplay=true` in the HTML, we were getting just `autoplay` for example.

2024-06-06 13:43 UTC, amglebihan commented on icons/play-video.svg
Done.

2024-06-06 14:03 UTC, santi-homps approved these changes

2024-06-06 15:40 UTC, jonatan-lledo-netcentric approved these changes

2024-06-10 13:27 UTC, amglebihan commented on blocks/v2-hero/v2-hero.css
> +  background-color: #b3976b;
Done.

2024-06-10 13:27 UTC, amglebihan commented on blocks/v2-hero/v2-hero.css
> +  background-color: #d9b781;
Done.

2024-06-13 12:54 UTC, merged