Magazine Tabbed Carousel with autoscroll #604
hlxsites/vg-macktrucks-com pull request #740
Opened 2024-06-06 21:16 UTC by santi-homps

Fix #604

Test URLs:
- Before: https://develop--vg-macktrucks-com--hlxsites.hlx.page/drafts/shomps/v2-magazine-tabbed-carousel
- After: https://604-mgz-tabbed-carousel--vg-macktrucks-com--hlxsites.hlx.page/drafts/shomps/v2-magazine-tabbed-carousel

2024-06-07 07:17 UTC, jonatan-lledo-netcentric commented
In the demo page, if there are less than 4 tabs, the scroll animation breaks. Also, if there is more than 1 block, the scrolling effect doesn't work always for all the blocks there

2024-06-07 08:36 UTC, amglebihan commented on blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.js
> +      const carouselItems = el.parentElement;
Consider splitting this function into smaller ones. We could extract the code and create a function that updates the active state from here...

2024-06-07 08:37 UTC, amglebihan commented on blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.js
> +      // Center navigation item
... and create another that handles centring the navigation item from here.

2024-06-07 08:37 UTC, amglebihan commented on blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.js
> +  function buildTabNavigation(title, category, index) {
Use an arrow function to be consistent with the rest of the code.

2024-06-07 08:42 UTC, amglebihan commented on blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.js
> +export default async function decorate(block) {
A suggestion, and same as above, I would try to make this code more modular. The decorate function should initialize the carousel, and delegate specific tasks to smaller functions. It contains a lot of code at the moment. That would make the code easier to read and to maintain. As we can use Copilot on the project, you could use it to give you hints on how to break down the code.

2024-06-07 08:49 UTC, amglebihan commented
- When the auto scrolling mode is on and you click on an item, it seems that it switches too fast to the next tab.
- Also, the styling of the active item changes in a weird manner sometimes.
- Should we handle other background colors? I guess that we could make use of CSS variables in more places if it should be the case.

2024-06-07 08:57 UTC, amglebihan commented on blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.js
> +  const autoScrollSwitch = document.createRange().createContextualFragment(`
It seems that the buttons are not accessible when tabbing. I would also add some styling for the focus-visible state of the buttons (same as the back to top inside the footer for example).
```
outline: 2px solid var(--border-focus);
outline-offset: 2px;
```

2024-06-11 07:27 UTC, alexiscoelho requested changes

2024-06-11 07:27 UTC, alexiscoelho commented on blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.js
> +      [carouselItems, navigation].forEach((c) => c.querySelectorAll('.active').forEach((i) => i.classList.remove('active')));
Not 100% sure about the practice you guys have been following on this project but it seems that you are using BEM then this `active` class should be a modifier. Maybe something like:
`v2-magazine-tabbed-carousel__navigation-item--active`

2024-06-11 07:27 UTC, alexiscoelho commented on blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.js
> +      [carouselItems, navigation].forEach((c) => c.querySelectorAll('.active').forEach((i) => i.classList.remove('active')));
Also, store the class name in a variable and reuse it across the code might be better

2024-06-11 14:03 UTC, alexiscoelho approved these changes

2024-06-17 09:19 UTC, amglebihan approved these changes

2024-06-17 14:10 UTC, merged