filters as placeholders & dynamic collage content #602
hlxsites/vg-macktrucks-com pull request #819
Opened 2024-08-01 14:46 UTC by jonatan-lledo-netcentric

## Notes

Filters are only added as placeholders. So it is missing styling and behaviour. only Show More button is working

#

Fix #602

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/
- After: https://602-blog-collage-block--vg-macktrucks-com--hlxsites.hlx.page/

2024-08-01 15:19 UTC, santi-homps commented on blocks/v2-explore-articles/v2-explore-articles.css
> +  font-size: 14px;
dont we have a `var` for this?

2024-08-01 15:20 UTC, santi-homps commented on blocks/v2-explore-articles/v2-explore-articles.css
> +  font-size: 14px;
same here

2024-08-01 15:21 UTC, santi-homps commented on blocks/v2-explore-articles/v2-explore-articles.css
> +  font-size: 20px;
and here

2024-08-01 15:25 UTC, santi-homps commented on blocks/v2-explore-articles/v2-explore-articles.css
> +    width: 231px;
IDK about this unit... would it be nicer to add `width: auto;` and then add the rest to the `padding`? I'm thinking in case in case other languages have longer words.

2024-08-01 15:41 UTC, santi-homps commented on blocks/v2-explore-articles/v2-explore-articles.css
> +  font-family: var(--ff-accents-medium);
I think this should be `var(--ff-testimonial)`

2024-08-01 16:57 UTC, alexiscoelho requested changes

2024-08-01 16:57 UTC, alexiscoelho commented on blocks/v2-explore-articles/v2-explore-articles.js
> +  extraFilters.classList.add(`${blockName}__extra-filters`);
Verify that each one of these elements exist before accessing `classList `

2024-08-01 16:57 UTC, alexiscoelho commented on blocks/v2-explore-articles/v2-explore-articles.js
> +  decorateShowingText(showingTextEl, allArticles);
And only do the following actions in case they exist

2024-08-01 16:57 UTC, alexiscoelho commented on blocks/v2-explore-articles/v2-explore-articles.js
> +  const sortByText = extraFilters.querySelector(':scope > p + p');
The first one is an element hence terminates in "El"
Do the same for the others

2024-08-01 16:57 UTC, alexiscoelho commented on blocks/v2-explore-articles/v2-explore-articles.js
> +  const urlDomain = window.location.origin;
Do you really need this `urlDomain`?

2024-08-01 16:57 UTC, alexiscoelho commented on blocks/v2-explore-articles/v2-explore-articles.js
> +      collageItemContainer.classList.add(`${blockName}__collage-item-container--hidden`);
This is not really a good approach.
You should just load the necessary elements and then when we click on show more we should load the next elements.
This is terms of performance is a really bad approach and can go wrong...

2024-08-01 16:57 UTC, alexiscoelho commented on blocks/v2-explore-articles/v2-explore-articles.js
> +    const hiddenItems = block.querySelectorAll(`.${blockName}__collage-item-container--hidden`);
Consider loading more items here instead of removing the hidden class

2024-08-02 10:20 UTC, jonatan-lledo-netcentric commented on blocks/v2-explore-articles/v2-explore-articles.css
> +  font-size: 14px;
I forgot about it. it's true, Thanks. updated

2024-08-02 10:21 UTC, jonatan-lledo-netcentric commented on blocks/v2-explore-articles/v2-explore-articles.css
> +  font-size: 14px;
updated too

2024-08-02 10:22 UTC, jonatan-lledo-netcentric commented on blocks/v2-explore-articles/v2-explore-articles.css
> +  font-size: 20px;
and updated too

2024-08-02 10:22 UTC, jonatan-lledo-netcentric commented on blocks/v2-explore-articles/v2-explore-articles.css
> +  font-family: var(--ff-accents-medium);
it's not the same GT font. good cath. fixed

2024-08-02 10:23 UTC, jonatan-lledo-netcentric commented on blocks/v2-explore-articles/v2-explore-articles.css
> +    width: 231px;
I replaced the magic number with just a fit-content. I hope this is better

2024-08-02 13:11 UTC, jonatan-lledo-netcentric commented on blocks/v2-explore-articles/v2-explore-articles.js
> +  const sortByText = extraFilters.querySelector(':scope > p + p');
I add 'El' to every variable that contains an Element

2024-08-02 13:12 UTC, jonatan-lledo-netcentric commented on blocks/v2-explore-articles/v2-explore-articles.js
> +  extraFilters.classList.add(`${blockName}__extra-filters`);
Added a conditional that checks if any of the elements is present or not

2024-08-02 13:14 UTC, jonatan-lledo-netcentric commented on blocks/v2-explore-articles/v2-explore-articles.js
> +  const urlDomain = window.location.origin;
I used to reduce the line length. but I removed it because is not needed

2024-08-02 16:06 UTC, jonatan-lledo-netcentric commented on blocks/v2-explore-articles/v2-explore-articles.js
> +      collageItemContainer.classList.add(`${blockName}__collage-item-container--hidden`);
Since `AllArticles` now contains all downloaded article JSON, I'll dynamically add more articles based on the initial predetermined quantity, instead of rendering everything and hiding extras.

2024-08-02 16:15 UTC, jonatan-lledo-netcentric commented on blocks/v2-explore-articles/v2-explore-articles.js
> +    const hiddenItems = block.querySelectorAll(`.${blockName}__collage-item-container--hidden`);
The 'show more' button now leverages the `AllArticles` variable to display up to 9 more items. Once the maximum is reached, the button is removed

2024-08-06 12:53 UTC, alexiscoelho requested changes

2024-08-06 12:53 UTC, alexiscoelho commented on blocks/v2-explore-articles/v2-explore-articles.js
> +    <div class="${blockName}__showing">
Move the classes that match `${blockName}__` to the CLASSES object.
Same for the rest of the occurrences in the file

2024-08-06 13:21 UTC, jonatan-lledo-netcentric commented on blocks/v2-explore-articles/v2-explore-articles.js
> +    <div class="${blockName}__showing">
I moved all the blockName classes to the CLASSES object

2024-08-06 14:01 UTC, alexiscoelho requested changes

2024-08-06 14:01 UTC, alexiscoelho commented on blocks/v2-explore-articles/v2-explore-articles.js
> +    <div class="${CLASSES.sortBy}">
You missed this

2024-08-06 14:22 UTC, jonatan-lledo-netcentric commented on blocks/v2-explore-articles/v2-explore-articles.js
> +    <div class="${CLASSES.sortBy}">
I also included its div container.

2024-08-06 14:25 UTC, alexiscoelho approved these changes

2024-08-06 20:34 UTC, santi-homps approved these changes

2024-08-09 14:06 UTC, amglebihan approved these changes

2024-08-09 14:09 UTC, merged