refactor Magazine template
hlxsites/vg-macktrucks-com pull request #825
Opened 2024-08-12 08:56 UTC by jonatan-lledo-netcentric

Fix https://github.com/hlxsites/vg-volvotrucks-us/issues/683

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/
- After: https://683-search-metadata-update--vg-macktrucks-com--hlxsites.hlx.page/

2024-08-12 09:27 UTC, amglebihan approved these changes

2024-08-14 08:08 UTC, alexiscoelho approved these changes

2024-08-14 08:17 UTC, alexiscoelho requested changes

2024-08-14 08:17 UTC, alexiscoelho commented on templates/magazine/magazine.js
> +  const tagItems = await getJsonFromUrl('/magazine/articles/tags.json');
Check if tagItems is truthy before moving forward

2024-08-14 08:17 UTC, alexiscoelho commented on templates/magazine/magazine.js
> +  const categories = tagItems && getValuesfromObjectsArray(tagItems.categories.data);
tagItems && tagItems.categories &&

2024-08-14 08:17 UTC, alexiscoelho commented on templates/magazine/magazine.js
> +  const trucks = tagItems && getValuesfromObjectsArray(tagItems.trucks.data);
tagItems && tagItems.trucks &&

2024-08-14 09:12 UTC, alexiscoelho approved these changes

2024-08-20 10:24 UTC, jonatan-lledo-netcentric commented on templates/magazine/magazine.js
> +  const tagItems = await getJsonFromUrl('/magazine/articles/tags.json');
done

2024-08-20 10:24 UTC, jonatan-lledo-netcentric commented on templates/magazine/magazine.js
> +  const categories = tagItems && getValuesfromObjectsArray(tagItems.categories.data);
done

2024-08-20 10:24 UTC, jonatan-lledo-netcentric commented on templates/magazine/magazine.js
> +  const trucks = tagItems && getValuesfromObjectsArray(tagItems.trucks.data);
done

2024-08-20 10:43 UTC, alexiscoelho approved these changes

2024-08-20 10:43 UTC, alexiscoelho commented on scripts/common.js
> + * @param {array} array - An array of objects
Should be: `{Array}`
And not: `{array}`
Same for the other array docs

2024-08-20 10:43 UTC, alexiscoelho commented on scripts/common.js
> +  const tagItems = await getJsonFromUrl('/magazine/articles/tags.json') || null;
getJsonFromUrl already returns null in case of failure

2024-08-20 10:55 UTC, jonatan-lledo-netcentric commented on scripts/common.js
> + * @param {array} array - An array of objects
done

2024-08-20 10:55 UTC, jonatan-lledo-netcentric commented on scripts/common.js
> +  const tagItems = await getJsonFromUrl('/magazine/articles/tags.json') || null;
done

2024-08-21 13:05 UTC, santi-homps approved these changes

2024-08-22 07:53 UTC, merged