72 video support
hlxsites/vg-macktrucks-com pull request #84
Opened 2023-05-11 08:36 UTC by TomaszDziezykNetcentric

Fix #72 

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/tdziezyk/video
- After: https://72-video-support--vg-macktrucks-com--hlxsites.hlx.page/drafts/tdziezyk/video

2023-05-11 11:03 UTC, Lakshmishri requested changes

2023-05-11 11:51 UTC, TomaszDziezykNetcentric commented on scripts/scripts.js
> +  const icon = document.createElement('i');
Fixed

2023-05-11 11:54 UTC, TomaszDziezykNetcentric commented on scripts/scripts.js
> +  const iframe = document.createElement('iframe');
Fixed

2023-05-11 11:57 UTC, TomaszDziezykNetcentric commented on common/modal/modal.js
> +  const closeButton = document.createElement('button');
Done

2023-05-11 12:56 UTC, jonatan-lledo-netcentric approved these changes

2023-05-11 17:03 UTC, jonatan-lledo-netcentric approved these changes

2023-05-12 08:46 UTC, Lakshmishri approved these changes

2023-05-12 08:46 UTC, merged