Breadcrumb block made authorable #770
hlxsites/vg-macktrucks-com pull request #877
Opened 2024-09-30 20:12 UTC by santi-homps

Fix #770

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/shomps/v2-breadcrumb
- After: https://770-breadcrumb-authorable--vg-macktrucks-com--hlxsites.hlx.page/drafts/shomps/v2-breadcrumb

2024-10-01 10:11 UTC, amglebihan commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  for (let i = 0; i < allEls.length; i += 2) {
It would be good to verify that allEls is not empty before executing this code.

2024-10-01 12:23 UTC, santi-homps commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  for (let i = 0; i < allEls.length; i += 2) {
Done

2024-10-03 09:08 UTC, amglebihan approved these changes

2024-10-07 09:33 UTC, alexiscoelho requested changes

2024-10-07 09:33 UTC, alexiscoelho commented on scripts/common.js
> +export function isLinkExternal(link) {
Can you please rename this function?
The name is misleading... Seems we are checking if the link is external and will receive the result.
But in reality it does an action in a certain condition.
Maybe something like, `addTargetBlankToExternalLink`

2024-10-07 09:33 UTC, alexiscoelho commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +const makeCustomUrl = (bread) => {
Maybe `generateCustomUrl` instead?

2024-10-07 09:33 UTC, alexiscoelho commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +const makeCustomUrl = (bread) => {
`bread` -> `breadcrumbBlock` or `breadcrumbBlockElement`

2024-10-07 09:33 UTC, alexiscoelho commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  const allEls = bread.querySelectorAll('p');
Please don't use this kind of logic to grab data from a block.
`p` tags are syntactic html tags that are wrapping text. Should not be used to grab the data.
You have a simple table made out of html divs. Use that instead. And you don't need to be doing this more complicated logic of grabbing a p tag content and the next element to get the value.

2024-10-07 09:33 UTC, alexiscoelho commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +    if (isCustomPath) isLinkExternal(crumb);
If you read this line of code you will understand your problem with the naming... 
Also, using these 'ifs' is a bad practice. Once I have time to review the lint rules this will not be allowed anymore ;)

2024-10-07 13:37 UTC, santi-homps commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +    if (isCustomPath) isLinkExternal(crumb);
Yes I agree but if I try to make it like this `isCustomPath && isLinkExternal(crumb);` the linter gives me this error: `Expected an assignment or function call and instead saw an expression`

2024-10-07 13:37 UTC, santi-homps commented on scripts/common.js
> +export function isLinkExternal(link) {
naming changes done!

2024-10-07 13:38 UTC, santi-homps commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  const allEls = bread.querySelectorAll('p');
totally right, changes this function quite a bit and it makes better sense now

2024-10-07 14:37 UTC, alexiscoelho approved these changes

2024-10-07 14:37 UTC, alexiscoelho commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  for (let i = 0; i < keysArray.length; i += 1) {
What about:
`for (const entryKey in breadcrumbBlockConfig) {`
`// value == breadcrumbBlockConfig[entryKey]`

2024-10-07 14:38 UTC, alexiscoelho commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  for (let i = 0; i < keysArray.length; i += 1) {
Or:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

2024-10-07 14:39 UTC, alexiscoelho commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +    if (isCustomPath) isLinkExternal(crumb);
I mean:
if (isCustomPath) {
    isLinkExternal(crumb);
}

2024-10-07 15:22 UTC, santi-homps commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  for (let i = 0; i < keysArray.length; i += 1) {
Done! also changed something in the `readBlockconfig` function since I needed the unsanitized string to maintain spaces and capitalization.

2024-10-07 17:27 UTC, santi-homps commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +    if (isCustomPath) isLinkExternal(crumb);
Oh, I can do that 👍

2024-10-07 17:51 UTC, alexiscoelho requested changes

2024-10-07 17:51 UTC, alexiscoelho commented on scripts/aem.js
> +        const name = sanitizeString ? toClassName(cols[0].textContent) : cols[0].textContent;
I have a strong feeling you should not do this.
I think that to use this, your config should instead have 3 cols.
First col -> key, etc...
Second -> Title
Third -> url

2024-10-07 17:51 UTC, alexiscoelho commented on scripts/aem.js
> +        const name = sanitizeString ? toClassName(cols[0].textContent) : cols[0].textContent;
Why this, because later we can come across that we need to update these files again...
By doing this we will be adding customisation that will be complicated to solve. More, the file will start to deviate from the Volvo version.
Customisations here should be well thought and done only if necessary

2024-10-07 18:07 UTC, alexiscoelho commented on scripts/aem.js
> +        const name = sanitizeString ? toClassName(cols[0].textContent) : cols[0].textContent;
My suggestion doesn't work :( 

```


function readKeyValuePairsFromBlock(block) {
  const config = {};
  block.querySelectorAll(':scope > div').forEach((row) => {
    if (row.children) {
      const cols = [...row.children];
      if (cols[1]) {
        const key = cols[0].textContent;
        const value = row.children[1].textContent;

        config[key] = value;
      }
    }
  });
  return config;
}
```

2024-10-07 18:39 UTC, santi-homps commented on scripts/aem.js
> +        const name = sanitizeString ? toClassName(cols[0].textContent) : cols[0].textContent;
ok maybe like this?

2024-10-09 13:38 UTC, alexiscoelho approved these changes

2024-10-10 12:34 UTC, merged