Exclude articles with no images from articles lists #828
hlxsites/vg-macktrucks-com pull request #893
Opened 2024-10-11 00:37 UTC by santi-homps

Fix #828

This PR also fixes some minor issues an cleans a bit the code that affects the following blocks:

v2-explore-articles
v2-magazine-tabbed-carousel
explore-articles
recommendations
recent-articles
(these last 2 can be found on the old magazine template)

Some test pages with the affected blocks are:

-https://828-exclude-articles-no-images--vg-macktrucks-com--hlxsites.hlx.page/drafts/shomps/v2-explore-articles
-https://828-exclude-articles-no-images--vg-macktrucks-com--hlxsites.hlx.page/drafts/shomps/v2-magazine-tabbed-carousel
-https://828-exclude-articles-no-images--vg-macktrucks-com--hlxsites.hlx.page/magazine/explore-articles
-https://828-exclude-articles-no-images--vg-macktrucks-com--hlxsites.hlx.page/magazine/articles/2023/august/choosing-mack-is-a-no-brainer

Test URLs:

Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/
After: https://828-exclude-articles-no-images--vg-macktrucks-com--hlxsites.hlx.page/

2024-10-11 08:26 UTC, alexiscoelho requested changes

2024-10-11 08:26 UTC, alexiscoelho commented on scripts/magazine-helper.js
> +import { getJsonFromUrl } from './common.js';
Please rename this file to `magazine.service.js`
Put it inside a services folder, can be inside of scripts for now...

2024-10-11 08:26 UTC, alexiscoelho commented on scripts/magazine-helper.js
> +export const removeArticlesWithNoImage = (articles) => {
Take a close look at how you are calling this method on the files:
`removeArticlesWithNoImage(allArticles);`
And how your method looks.
You are returning the articles, but not using the return and changing the array by reference.
This in terms of programming is wrong and can lead to unexpected behaviours.
Instead, copy the array, do the changes, return the array and use the returned value. The provided array to this method should not change!

2024-10-11 12:50 UTC, santi-homps commented on scripts/magazine-helper.js
> +import { getJsonFromUrl } from './common.js';
Done

2024-10-11 12:59 UTC, santi-homps commented on scripts/magazine-helper.js
> +export const removeArticlesWithNoImage = (articles) => {
Done!

2024-10-11 13:51 UTC, alexiscoelho approved these changes

2024-10-14 12:21 UTC, amglebihan approved these changes

2024-10-15 12:36 UTC, merged