V2 Social Block #748
hlxsites/vg-macktrucks-com pull request #897
Opened 2024-10-15 18:07 UTC by santi-homps

Fix #748

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/shomps/v2-social-block-template
- After: https://748-v2-social-block--vg-macktrucks-com--hlxsites.hlx.page/drafts/shomps/v2-social-block-template

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/shomps/v2-social-block
- After: https://748-v2-social-block--vg-macktrucks-com--hlxsites.hlx.page/drafts/shomps/v2-social-block

2024-10-15 21:53 UTC, jonatan-lledo-netcentric commented on blocks/v2-social-block/v2-social-block.js
> +  const shareURLs = [
Wouldn't it be better to have these values ​​in the constants file?

2024-10-16 12:14 UTC, santi-homps commented on blocks/v2-social-block/v2-social-block.js
> +  const shareURLs = [
It could be... though I dont know what could be the benefits and didnt want to clog that file any more

2024-10-16 12:26 UTC, jonatan-lledo-netcentric commented on blocks/v2-social-block/v2-social-block.js
> +  const shareURLs = [
then it's ok as it is

2024-10-16 12:37 UTC, alexiscoelho requested changes

2024-10-16 12:37 UTC, alexiscoelho commented on blocks/v2-social-block/v2-social-block.js
> +      anchor.classList.add('tooltip', 'tooltip--top');
Why all of this html, classes and so on not be a template? 
Like you can see on macktrucks:
/vg-macktrucks-com/blocks/v2-explore-articles/v2-explore-articles.js

2024-10-16 12:41 UTC, alexiscoelho commented on blocks/v2-social-block/v2-social-block.js
> +      anchor.classList.add('tooltip', 'tooltip--top');
By having the code as you have it is not easily maintainable, you don't have any idea of the end result by looking at the code (at least not easily), it also complicates a lot the readability

2024-10-17 18:06 UTC, santi-homps commented on blocks/v2-social-block/v2-social-block.js
> +      anchor.classList.add('tooltip', 'tooltip--top');
Refactor done!

2024-10-18 06:53 UTC, jonatan-lledo-netcentric approved these changes

2024-10-18 09:18 UTC, alexiscoelho approved these changes

2024-10-18 13:46 UTC, merged