Feat #28: Hotspots block
hlxsites/vg-macktrucks-com pull request #94
Opened 2023-05-17 05:41 UTC by synox

Fix #28

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/
- After: https://<branch>--vg-macktrucks-com--hlxsites.hlx.page/

2023-05-17 15:18 UTC, Lakshmishri commented on blocks/features/features.js
> +    const h4 = document.createElement('h4');
We can use createElement function here  and also avoid using innerHTML as its vulnerable. Can we avoid and use innerText or textContent unless we are copying also other tags apart from text from title ?
```
 const h4 = createElement('h4', 'feature-title');
 h4.innerText =  title.innerText;
 ```

2023-05-17 15:27 UTC, Lakshmishri commented on blocks/hotspots/hotspots.js
> +  const iconLink = document.createElement('a');
Same as above
```
const iconProps = { href:'#', style: "left:hotspot.positionLeft;top: hotspot.positionTop", dataset: hotspot.id.toString()};
const iconLink =  createElement('a', 'hotspot-icon', iconProps);
const imgTag = createElement(img, '', {src: "../../icons/hotspot.png", alt: hotspot.title.textContent });

iconLink.appendChild(imgTag);

iconLink.onclick = (event) => handleClickHotspot(
  event,
  iconLink,
  hotspot.id,
  block,
);
```

2023-05-17 15:29 UTC, jonatan-lledo-netcentric requested changes
if a hotspot is below a text, is not clickable, unless the text is below without z-index or with a value of 0

2023-05-17 15:34 UTC, Lakshmishri requested changes
Please let me know if u disagree

2023-05-17 18:32 UTC, synox commented on blocks/features/features.js
> +    const h4 = document.createElement('h4');
I use the HTML because the title contains tags that are needed. e.g. `<sup class="r">®</sup>`. The HTML is safe as it is coming from Franklin content bus. 

I will change the code to use  `createElement` where appropriate 👍

2023-05-17 19:44 UTC, synox commented on blocks/hotspots/hotspots.css
> +    z-index: 2;
Good find. fixed

2023-05-18 06:33 UTC, jonatan-lledo-netcentric approved these changes

2023-05-18 08:15 UTC, TomaszDziezykNetcentric commented
@synox 
The text on mobile has some problems fitting in the container.
<img width="466" alt="obraz" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125962117/1ad04934-f26e-497f-a885-0e2661248304">

2023-05-19 08:21 UTC, Lakshmishri submitted a review, later dismissed
<img width="954" alt="Screenshot 2023-05-19 at 10 18 37" src="https://github.com/hlxsites/vg-macktrucks-com/assets/4208604/cedd96b0-bfae-4c99-991a-2116d3f2e517">
I  don't see any hover state in existing implementation

2023-05-22 18:23 UTC, merged